version: '3.9'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:6.1.1-php7.4-apache
    ports:
      - 80:80
    volumes:
      - ./wp:/var/www/html/
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 
      WORDPRESS_DB_NAME: name_project

volumes:
    db_data:
    wp: